import Head from 'next/head'
import HomeTemplate from '@templates/HomeTemplate'
import { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Football World Cup Score Board</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomeTemplate /> 
    </>
  )
}

export default Home